//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.09 at 09:44:48 AM CEST 
//


package cz.zcu.kiv.bp.uniplayer.bindings;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.zcu.kiv.bp.uniplayer.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Project_QNAME = new QName("", "project");
    private final static QName _TValueShort_QNAME = new QName("", "short");
    private final static QName _TValueBase64_QNAME = new QName("", "base64");
    private final static QName _TValueByte_QNAME = new QName("", "byte");
    private final static QName _TValueInt_QNAME = new QName("", "int");
    private final static QName _TValueString_QNAME = new QName("", "string");
    private final static QName _TValueBigDecimal_QNAME = new QName("", "BigDecimal");
    private final static QName _TValueBoolean_QNAME = new QName("", "boolean");
    private final static QName _TValueBigInteger_QNAME = new QName("", "BigInteger");
    private final static QName _TValueDouble_QNAME = new QName("", "double");
    private final static QName _TValueLong_QNAME = new QName("", "long");
    private final static QName _TValueFloat_QNAME = new QName("", "float");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.zcu.kiv.bp.uniplayer.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TProject }
     * 
     */
    public TProject createTProject() {
        return new TProject();
    }

    /**
     * Create an instance of {@link TExponential }
     * 
     */
    public TExponential createTExponential() {
        return new TExponential();
    }

    /**
     * Create an instance of {@link TValue }
     * 
     */
    public TValue createTValue() {
        return new TValue();
    }

    /**
     * Create an instance of {@link TBigIntegerList }
     * 
     */
    public TBigIntegerList createTBigIntegerList() {
        return new TBigIntegerList();
    }

    /**
     * Create an instance of {@link TActionsList }
     * 
     */
    public TActionsList createTActionsList() {
        return new TActionsList();
    }

    /**
     * Create an instance of {@link TCall }
     * 
     */
    public TCall createTCall() {
        return new TCall();
    }

    /**
     * Create an instance of {@link TRecurrence }
     * 
     */
    public TRecurrence createTRecurrence() {
        return new TRecurrence();
    }

    /**
     * Create an instance of {@link TAction }
     * 
     */
    public TAction createTAction() {
        return new TAction();
    }

    /**
     * Create an instance of {@link TEvent }
     * 
     */
    public TEvent createTEvent() {
        return new TEvent();
    }

    /**
     * Create an instance of {@link TByteList }
     * 
     */
    public TByteList createTByteList() {
        return new TByteList();
    }

    /**
     * Create an instance of {@link TEquidistant }
     * 
     */
    public TEquidistant createTEquidistant() {
        return new TEquidistant();
    }

    /**
     * Create an instance of {@link TByteArrayList }
     * 
     */
    public TByteArrayList createTByteArrayList() {
        return new TByteArrayList();
    }

    /**
     * Create an instance of {@link TLongList }
     * 
     */
    public TLongList createTLongList() {
        return new TLongList();
    }

    /**
     * Create an instance of {@link TShortList }
     * 
     */
    public TShortList createTShortList() {
        return new TShortList();
    }

    /**
     * Create an instance of {@link TIntList }
     * 
     */
    public TIntList createTIntList() {
        return new TIntList();
    }

    /**
     * Create an instance of {@link TGaussian }
     * 
     */
    public TGaussian createTGaussian() {
        return new TGaussian();
    }

    /**
     * Create an instance of {@link TCommand }
     * 
     */
    public TCommand createTCommand() {
        return new TCommand();
    }

    /**
     * Create an instance of {@link TSettings }
     * 
     */
    public TSettings createTSettings() {
        return new TSettings();
    }

    /**
     * Create an instance of {@link TFileList }
     * 
     */
    public TFileList createTFileList() {
        return new TFileList();
    }

    /**
     * Create an instance of {@link TBigDecimalList }
     * 
     */
    public TBigDecimalList createTBigDecimalList() {
        return new TBigDecimalList();
    }

    /**
     * Create an instance of {@link TArgumentsList }
     * 
     */
    public TArgumentsList createTArgumentsList() {
        return new TArgumentsList();
    }

    /**
     * Create an instance of {@link TFloatList }
     * 
     */
    public TFloatList createTFloatList() {
        return new TFloatList();
    }

    /**
     * Create an instance of {@link TCollection }
     * 
     */
    public TCollection createTCollection() {
        return new TCollection();
    }

    /**
     * Create an instance of {@link TStringList }
     * 
     */
    public TStringList createTStringList() {
        return new TStringList();
    }

    /**
     * Create an instance of {@link TArgument }
     * 
     */
    public TArgument createTArgument() {
        return new TArgument();
    }

    /**
     * Create an instance of {@link TBooleanList }
     * 
     */
    public TBooleanList createTBooleanList() {
        return new TBooleanList();
    }

    /**
     * Create an instance of {@link TDoubleList }
     * 
     */
    public TDoubleList createTDoubleList() {
        return new TDoubleList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "project")
    public JAXBElement<TProject> createProject(TProject value) {
        return new JAXBElement<TProject>(_Project_QNAME, TProject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "short", scope = TValue.class)
    public JAXBElement<Short> createTValueShort(Short value) {
        return new JAXBElement<Short>(_TValueShort_QNAME, Short.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "base64", scope = TValue.class)
    public JAXBElement<byte[]> createTValueBase64(byte[] value) {
        return new JAXBElement<byte[]>(_TValueBase64_QNAME, byte[].class, TValue.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "byte", scope = TValue.class)
    public JAXBElement<Byte> createTValueByte(Byte value) {
        return new JAXBElement<Byte>(_TValueByte_QNAME, Byte.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "int", scope = TValue.class)
    public JAXBElement<Integer> createTValueInt(Integer value) {
        return new JAXBElement<Integer>(_TValueInt_QNAME, Integer.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "string", scope = TValue.class)
    public JAXBElement<String> createTValueString(String value) {
        return new JAXBElement<String>(_TValueString_QNAME, String.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigDecimal", scope = TValue.class)
    public JAXBElement<BigDecimal> createTValueBigDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TValueBigDecimal_QNAME, BigDecimal.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "boolean", scope = TValue.class)
    public JAXBElement<Boolean> createTValueBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_TValueBoolean_QNAME, Boolean.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BigInteger", scope = TValue.class)
    public JAXBElement<BigInteger> createTValueBigInteger(BigInteger value) {
        return new JAXBElement<BigInteger>(_TValueBigInteger_QNAME, BigInteger.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "double", scope = TValue.class)
    public JAXBElement<Double> createTValueDouble(Double value) {
        return new JAXBElement<Double>(_TValueDouble_QNAME, Double.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "long", scope = TValue.class)
    public JAXBElement<Long> createTValueLong(Long value) {
        return new JAXBElement<Long>(_TValueLong_QNAME, Long.class, TValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "float", scope = TValue.class)
    public JAXBElement<Float> createTValueFloat(Float value) {
        return new JAXBElement<Float>(_TValueFloat_QNAME, Float.class, TValue.class, value);
    }

}
