//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.19 at 09:04:38 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
	xmlns = {
	@javax.xml.bind.annotation.XmlNs(
	    prefix = cz.zcu.kiv.bp.uniplayer.bindings.basics.MyPrefixMapper.SCENARIO_PREFIX,
	    namespaceURI = cz.zcu.kiv.bp.uniplayer.bindings.basics.MyPrefixMapper.SCENARIO_URI //"http://www.kiv.zcu.cz/component-testing/simulation/scenario/player"
	)},
	namespace = cz.zcu.kiv.bp.uniplayer.bindings.basics.MyPrefixMapper.SCENARIO_URI,
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED	
)
package cz.zcu.kiv.bp.uniplayer.bindings;
