//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.19 at 10:11:55 AM CEST 
//


package cz.zcu.kiv.bp.uniplayer.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import cz.zcu.kiv.bp.datatypes.bindings.TCustomTypesSupport;


/**
 * <p>Java class for TSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="time-limit" type="{http://www.kiv.zcu.cz/component-testing/player}TPositiveLong" minOccurs="0"/>
 *         &lt;element name="simul-step-delay" type="{http://www.kiv.zcu.cz/component-testing/player}TNonNegativeLong" minOccurs="0"/>
 *         &lt;element ref="{http://www.kiv.zcu.cz/component-testing/types}custom-types-support" />
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "TSettings", propOrder = {
    "timeLimit",
    "simulStepDelay",
    "customTypesSupport"
})
public class TSettings {

    protected Long timeLimit = Long.MAX_VALUE;
    
    protected Long simulStepDelay = 0L;

    protected TCustomTypesSupport customTypesSupport;
    
    /**
     * Gets the value of the timeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @XmlElement(name = "time-limit")
    public Long getTimeLimit() {
        return (timeLimit.longValue() == Long.MAX_VALUE) ? null : timeLimit;
    }

    /**
     * Sets the value of the timeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeLimit(Long value) {
        this.timeLimit = value;
    }

    /**
     * Gets the value of the simulStepDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @XmlElement(name = "simul-step-delay")
    public Long getSimulStepDelay() {
        return (simulStepDelay.longValue() == 0L) ? null : simulStepDelay;
    }

    /**
     * Sets the value of the simulStepDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSimulStepDelay(Long value) {
        this.simulStepDelay = value;
    }

    @XmlElement(
    	namespace = cz.zcu.kiv.bp.namespaces.DataTypes.SCENARIO_URI,
    	name = "custom-types-support", required = false
    )
	public TCustomTypesSupport getCustomTypesSupport() {
		if (customTypesSupport == null) {
			customTypesSupport = new TCustomTypesSupport();
		}
		return customTypesSupport;
	}

	public void setCustomTypesSupport(TCustomTypesSupport customTypesSupport) {
		this.customTypesSupport = customTypesSupport;
	}
}
