//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 08:12:58 PM CEST 
//


package cz.zcu.kiv.bp.uniplayer.bindings;

import java.io.File;
import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import cz.zcu.kiv.bp.uniplayer.bindings.adapted.*;


/**
 * <p>Java class for TValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BigInteger" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="long" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="int" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="short" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="byte" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="BigDecimal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="double" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="float" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="file" type="{http://www.kiv.zcu.cz/component-testing/player}TFile"/>
 *         &lt;element name="bool" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="strings" type="{http://www.kiv.zcu.cz/component-testing/player}TStringCollection"/>
 *         &lt;element name="BigInts" type="{http://www.kiv.zcu.cz/component-testing/player}TBigIntegerCollection"/>
 *         &lt;element name="longs" type="{http://www.kiv.zcu.cz/component-testing/player}TLongCollection"/>
 *         &lt;element name="ints" type="{http://www.kiv.zcu.cz/component-testing/player}TIntCollection"/>
 *         &lt;element name="shorts" type="{http://www.kiv.zcu.cz/component-testing/player}TShortCollection"/>
 *         &lt;element name="bytes" type="{http://www.kiv.zcu.cz/component-testing/player}TByteCollection"/>
 *         &lt;element name="BigDecimals" type="{http://www.kiv.zcu.cz/component-testing/player}TBigDecimalCollection"/>
 *         &lt;element name="doubles" type="{http://www.kiv.zcu.cz/component-testing/player}TDoubleCollection"/>
 *         &lt;element name="floats" type="{http://www.kiv.zcu.cz/component-testing/player}TFloatCollection"/>
 *         &lt;element name="bools" type="{http://www.kiv.zcu.cz/component-testing/player}TBooleanCollection"/>
 *         &lt;element name="files" type="{http://www.kiv.zcu.cz/component-testing/player}TFileCollection"/>
 *         &lt;element name="null" type="{http://www.kiv.zcu.cz/component-testing/player}TNull"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TValue", propOrder = {
    "string",
    "bigInteger",
    "_long",
    "_int",
    "_short",
    "_byte",
    "bigDecimal",
    "_double",
    "_float",
    "file",
    "bool",
    "strings",
    "bigInts",
    "longs",
    "ints",
    "shorts",
    "bytes",
    "bigDecimals",
    "doubles",
    "floats",
    "bools",
    "files",
    "_null"
})
@XmlSeeAlso({
    TArgument.class
})
public class TValue {

    protected String string;
    
    @XmlElement(name = "BigInteger")
    protected BigInteger bigInteger;
    
    @XmlElement(name = "long")
    protected Long _long;
    
    @XmlElement(name = "int")
    protected Integer _int;
    
    @XmlElement(name = "short")
    protected Short _short;
    
    @XmlElement(name = "byte")
    protected Byte _byte;
    
    @XmlElement(name = "BigDecimal")
    protected BigDecimal bigDecimal;
    
    @XmlElement(name = "double")
    protected Double _double;

    @XmlElement(name = "float")
    protected Float _float;
    
    @XmlElement(name = "File", type = String.class)
    @XmlSchemaType(name = "anyURI")
    @XmlJavaTypeAdapter(FileAdapter.class)
    protected File file;
    
    protected Boolean bool;
    
    @XmlElement(type = TStringCollection.class)
    @XmlJavaTypeAdapter(StringCollectionAdapter.class)
    protected StringCollection strings;
    
    @XmlElement(name = "BigInts", type = TBigIntegerCollection.class)
    @XmlJavaTypeAdapter(BigIntegerCollectionAdapter.class)
    protected BigIntegerCollection bigInts;
    
    @XmlElement(type = TLongCollection.class)
    @XmlJavaTypeAdapter(LongCollectionAdapter.class)
    protected LongCollection longs;
    
    @XmlElement(type = TIntCollection.class)
    @XmlJavaTypeAdapter(IntegerCollectionAdapter.class)
    protected IntegerCollection ints;
    
    @XmlElement(type = TShortCollection.class)
    @XmlJavaTypeAdapter(ShortCollectionAdapter.class)
    protected ShortCollection shorts;
    
    @XmlElement(type = TByteCollection.class)
    @XmlJavaTypeAdapter(ByteCollectionAdapter.class)
    protected ByteCollection bytes;
    
    @XmlElement(name = "BigDecimals", type = TBigDecimalCollection.class)
    @XmlJavaTypeAdapter(BigDecimalCollectionAdapter.class)
    protected BigDecimalCollection bigDecimals;
    
    @XmlElement(type = TDoubleCollection.class)
    @XmlJavaTypeAdapter(DoubleCollectionAdapter.class)
    protected DoubleCollection doubles;
    
    @XmlElement(type = TFloatCollection.class)
    @XmlJavaTypeAdapter(FloatCollectionAdapter.class)
    protected FloatCollection floats;
    
    @XmlElement(type = TBooleanCollection.class)
    @XmlJavaTypeAdapter(BooleanCollectionAdapter.class)
    protected BooleanCollection bools;
    
    @XmlElement(name = "Files", type = TFileCollection.class)
    @XmlJavaTypeAdapter(FileCollectionAdapter.class)
    protected FileCollection files;
    
    @XmlElement(name = "null")
    protected TNull _null;

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setString(String value) {
        this.string = value;
    }

    /**
     * Gets the value of the bigInteger property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBigInteger() {
        return bigInteger;
    }

    /**
     * Sets the value of the bigInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBigInteger(BigInteger value) {
        this.bigInteger = value;
    }

    /**
     * Gets the value of the long property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLong() {
        return _long;
    }

    /**
     * Sets the value of the long property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLong(Long value) {
        this._long = value;
    }

    /**
     * Gets the value of the int property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInt() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInt(Integer value) {
        this._int = value;
    }

    /**
     * Gets the value of the short property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getShort() {
        return _short;
    }

    /**
     * Sets the value of the short property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setShort(Short value) {
        this._short = value;
    }

    /**
     * Gets the value of the byte property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getByte() {
        return _byte;
    }

    /**
     * Sets the value of the byte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setByte(Byte value) {
        this._byte = value;
    }

    /**
     * Gets the value of the bigDecimal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBigDecimal() {
        return bigDecimal;
    }

    /**
     * Sets the value of the bigDecimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBigDecimal(BigDecimal value) {
        this.bigDecimal = value;
    }

    /**
     * Gets the value of the double property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDouble() {
        return _double;
    }

    /**
     * Sets the value of the double property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDouble(Double value) {
        this._double = value;
    }

    /**
     * Gets the value of the float property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFloat() {
        return _float;
    }

    /**
     * Sets the value of the float property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFloat(Float value) {
        this._float = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFile(File value) {
        this.file = value;
    }

    /**
     * Gets the value of the bool property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getBool() {
        return bool;
    }

    /**
     * Sets the value of the bool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBool(Boolean value) {
        this.bool = value;
    }

    /**
     * Gets the value of the strings property.
     * 
     * @return
     *     possible object is
     *     {@link TStringCollection }
     *     
     */
    public MyCollection<String> getStrings() {
        return strings;
    }

    /**
     * Sets the value of the strings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStringCollection }
     *     
     */
    public void setStrings(StringCollection value) {
        this.strings = value;
    }

    /**
     * Gets the value of the bigInts property.
     * 
     * @return
     *     possible object is
     *     {@link TBigIntegerCollection }
     *     
     */
    public MyCollection<BigInteger> getBigInts() {
        return bigInts;
    }

    /**
     * Sets the value of the bigInts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBigIntegerCollection }
     *     
     */
    public void setBigInts(BigIntegerCollection value) {
        this.bigInts = value;
    }

    /**
     * Gets the value of the longs property.
     * 
     * @return
     *     possible object is
     *     {@link TLongCollection }
     *     
     */
    public MyCollection<Long> getLongs() {
        return longs;
    }

    /**
     * Sets the value of the longs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLongCollection }
     *     
     */
    public void setLongs(LongCollection value) {
        this.longs = value;
    }

    /**
     * Gets the value of the ints property.
     * 
     * @return
     *     possible object is
     *     {@link TIntCollection }
     *     
     */
    public MyCollection<Integer> getInts() {
        return ints;
    }

    /**
     * Sets the value of the ints property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIntCollection }
     *     
     */
    public void setInts(IntegerCollection value) {
        this.ints = value;
    }

    /**
     * Gets the value of the shorts property.
     * 
     * @return
     *     possible object is
     *     {@link TShortCollection }
     *     
     */
    public MyCollection<Short> getShorts() {
        return shorts;
    }

    /**
     * Sets the value of the shorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TShortCollection }
     *     
     */
    public void setShorts(ShortCollection value) {
        this.shorts = value;
    }

    /**
     * Gets the value of the bytes property.
     * 
     * @return
     *     possible object is
     *     {@link TByteCollection }
     *     
     */
    public MyCollection<Byte> getBytes() {
        return bytes;
    }

    /**
     * Sets the value of the bytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TByteCollection }
     *     
     */
    public void setBytes(ByteCollection value) {
        this.bytes = value;
    }

    /**
     * Gets the value of the bigDecimals property.
     * 
     * @return
     *     possible object is
     *     {@link TBigDecimalCollection }
     *     
     */
    public MyCollection<BigDecimal> getBigDecimals() {
        return bigDecimals;
    }

    /**
     * Sets the value of the bigDecimals property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBigDecimalCollection }
     *     
     */
    public void setBigDecimals(BigDecimalCollection value) {
        this.bigDecimals = value;
    }

    /**
     * Gets the value of the doubles property.
     * 
     * @return
     *     possible object is
     *     {@link TDoubleCollection }
     *     
     */
    public MyCollection<Double> getDoubles() {
        return doubles;
    }

    /**
     * Sets the value of the doubles property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDoubleCollection }
     *     
     */
    public void setDoubles(DoubleCollection value) {
        this.doubles = value;
    }

    /**
     * Gets the value of the floats property.
     * 
     * @return
     *     possible object is
     *     {@link TFloatCollection }
     *     
     */
    public MyCollection<Float> getFloats() {
        return floats;
    }

    /**
     * Sets the value of the floats property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFloatCollection }
     *     
     */
    public void setFloats(FloatCollection value) {
        this.floats = value;
    }

    /**
     * Gets the value of the bools property.
     * 
     * @return
     *     possible object is
     *     {@link TBooleanCollection }
     *     
     */
    public MyCollection<Boolean> getBools() {
        return bools;
    }

    /**
     * Sets the value of the bools property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBooleanCollection }
     *     
     */
    public void setBools(BooleanCollection value) {
        this.bools = value;
    }

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link TFileCollection }
     *     
     */
    public MyCollection<File> getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFileCollection }
     *     
     */
    public void setFiles(FileCollection value) {
        this.files = value;
    }

    /**
     * Gets the value of the null property.
     * 
     * @return
     *     possible object is
     *     {@link TNull }
     *     
     */
    public TNull getNull() {
        return _null;
    }

    /**
     * Sets the value of the null property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNull }
     *     
     */
    public void setNull(TNull value) {
        this._null = value;
    }

    @Override
    public String toString()
    {
    	StringBuilder sb = new StringBuilder();
    	
    	for (Field field : TValue.class/*this.getClass()*/.getDeclaredFields())
    	{
    		try {
				Object val = field.get(this);
				if (val == null) { /*System.out.println("field " + field.getName() + " is null.");*/ continue; }
				sb.append(field.getName()).append(" - ").append(field.getType().getSimpleName()).append(": ").append(val);
			} catch (IllegalArgumentException | IllegalAccessException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    	
    	return sb.toString();
    }
}
