//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 04:41:25 PM CEST 
//


package cz.zcu.kiv.bp.uniplayer.bindings.old.basics;

//import java.lang.reflect.Method;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import cz.zcu.kiv.bp.uniplayer.bindings.old.*;


/**
 * Common superclass for all T?CollectionItem wrapper classes
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TCollectionItem")
@XmlSeeAlso({
    TLongCollection.Item.class,
    TIntCollection.Item.class,
    TBooleanCollection.Item.class,
    TByteCollection.Item.class,
    TFloatCollection.Item.class,
    TBigDecimalCollection.Item.class,
    TBigIntegerCollection.Item.class,
    TDoubleCollection.Item.class,
    TStringCollection.Item.class,
    TFileCollection.Item.class,
    TShortCollection.Item.class
})
public abstract class TCollectionItem<T> {

	/**
	 * index for ordering purposes
	 */
    @XmlAttribute(name = "ord-num", required = true)
    protected int ordNum;

    /**
     * Gets the value of the ordNum property.
     * 
     */
    public int getOrdNum() {
        return ordNum;
    }

    /**
     * Sets the value of the ordNum property.
     * 
     */
    public void setOrdNum(int value) {
        this.ordNum = value;
    }

    /**
     * Gets item's value. Parameterized method used for type safety in CollectionAdapter.
     * @return item's value
     */
    public abstract T getValue();
    
    /**
     * Sets item's value. Parameterized method used for type safety in CollectionAdapter.
     * @param value
     */
    public abstract void setValue(T value);

}
