//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 06:16:23 PM CET 
//


package cz.zcu.kiv.bp.datatypes.bindings;

import java.io.File;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import cz.zcu.kiv.bp.datatypes.bindings.adapted.*;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.zcu.kiv.bp.datatypes.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{
    private final static QName _Null_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Null");
    private final static QName _File_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "File");
    private final static QName _Files_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Files");
    private final static QName _BigInts_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "BigInts");
    private final static QName _Longs_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Longs");
    private final static QName _Ints_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Ints");
    private final static QName _Shorts_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Shorts");
    private final static QName _Bytes_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Bytes");
    private final static QName _BigDecimals_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "BigDecimals");
    private final static QName _Doubles_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Doubles");
    private final static QName _Floats_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Floats");
    private final static QName _Booleans_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Booleans");
    private final static QName _Strings_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/types", "Strings");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.zcu.kiv.bp.datatypes.bindings.gen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TByteCollection }
     * 
     */
    public TByteCollection createTByteCollection() {
        return new TByteCollection();
    }

    /**
     * Create an instance of {@link TLongCollection }
     * 
     */
    public TLongCollection createTLongCollection() {
        return new TLongCollection();
    }

    /**
     * Create an instance of {@link TBigDecimalCollection }
     * 
     */
    public TBigDecimalCollection createTBigDecimalCollection() {
        return new TBigDecimalCollection();
    }

    /**
     * Create an instance of {@link TShortCollection }
     * 
     */
    public TShortCollection createTShortCollection() {
        return new TShortCollection();
    }

    /**
     * Create an instance of {@link TFloatCollection }
     * 
     */
    public TFloatCollection createTFloatCollection() {
        return new TFloatCollection();
    }

    /**
     * Create an instance of {@link TBigIntegerCollection }
     * 
     */
    public TBigIntegerCollection createTBigIntegerCollection() {
        return new TBigIntegerCollection();
    }

    /**
     * Create an instance of {@link TFileCollection }
     * 
     */
    public TFileCollection createTFileCollection() {
        return new TFileCollection();
    }

    /**
     * Create an instance of {@link TBooleanCollection }
     * 
     */
    public TBooleanCollection createTBooleanCollection() {
        return new TBooleanCollection();
    }

    /**
     * Create an instance of {@link TDoubleCollection }
     * 
     */
    public TDoubleCollection createTDoubleCollection() {
        return new TDoubleCollection();
    }

    /**
     * Create an instance of {@link TStringCollection }
     * 
     */
    public TStringCollection createTStringCollection() {
        return new TStringCollection();
    }

    /**
     * Create an instance of {@link TIntCollection }
     * 
     */
    public TIntCollection createTIntCollection() {
        return new TIntCollection();
    }

    /**
     * Create an instance of {@link TNull }
     * 
     */
    public TNull createTNull() {
        return new TNull();
    }

    /**
     * Create an instance of {@link TByteCollection.Item }
     * 
     */
    public TByteCollection.Item createTByteCollectionItem() {
        return new TByteCollection.Item();
    }

    /**
     * Create an instance of {@link TLongCollection.Item }
     * 
     */
    public TLongCollection.Item createTLongCollectionItem() {
        return new TLongCollection.Item();
    }

    /**
     * Create an instance of {@link TBigDecimalCollection.Item }
     * 
     */
    public TBigDecimalCollection.Item createTBigDecimalCollectionItem() {
        return new TBigDecimalCollection.Item();
    }

    /**
     * Create an instance of {@link TShortCollection.Item }
     * 
     */
    public TShortCollection.Item createTShortCollectionItem() {
        return new TShortCollection.Item();
    }

    /**
     * Create an instance of {@link TFloatCollection.Item }
     * 
     */
    public TFloatCollection.Item createTFloatCollectionItem() {
        return new TFloatCollection.Item();
    }

    /**
     * Create an instance of {@link TBigIntegerCollection.Item }
     * 
     */
    public TBigIntegerCollection.Item createTBigIntegerCollectionItem() {
        return new TBigIntegerCollection.Item();
    }

    /**
     * Create an instance of {@link TFileCollection.Item }
     * 
     */
    public TFileCollection.Item createTFileCollectionItem() {
        return new TFileCollection.Item();
    }

    /**
     * Create an instance of {@link TBooleanCollection.Item }
     * 
     */
    public TBooleanCollection.Item createTBooleanCollectionItem() {
        return new TBooleanCollection.Item();
    }

    /**
     * Create an instance of {@link TDoubleCollection.Item }
     * 
     */
    public TDoubleCollection.Item createTDoubleCollectionItem() {
        return new TDoubleCollection.Item();
    }

    /**
     * Create an instance of {@link TStringCollection.Item }
     * 
     */
    public TStringCollection.Item createTStringCollectionItem() {
        return new TStringCollection.Item();
    }

    /**
     * Create an instance of {@link TIntCollection.Item }
     * 
     */
    public TIntCollection.Item createTIntCollectionItem() {
        return new TIntCollection.Item();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNull }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Null")
    public JAXBElement<TNull> createNull(TNull value) {
        return new JAXBElement<TNull>(_Null_QNAME, TNull.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLongCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Longs")
    public JAXBElement<TLongCollection> createLongs(TLongCollection value) {
        return new JAXBElement<TLongCollection>(_Longs_QNAME, TLongCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBigDecimalCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "BigDecimals")
    public JAXBElement<TBigDecimalCollection> createBigDecimals(TBigDecimalCollection value) {
        return new JAXBElement<TBigDecimalCollection>(_BigDecimals_QNAME, TBigDecimalCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TByteCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Bytes")
    public JAXBElement<TByteCollection> createBytes(TByteCollection value) {
        return new JAXBElement<TByteCollection>(_Bytes_QNAME, TByteCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TShortCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Shorts")
    public JAXBElement<TShortCollection> createShorts(TShortCollection value) {
        return new JAXBElement<TShortCollection>(_Shorts_QNAME, TShortCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "File")
    @XmlJavaTypeAdapter(FileAdapter.class)
    public JAXBElement<File> createFile(File value) {
        return new JAXBElement<File>(_File_QNAME, File.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFloatCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Floats")
    public JAXBElement<TFloatCollection> createFloats(TFloatCollection value) {
        return new JAXBElement<TFloatCollection>(_Floats_QNAME, TFloatCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBigIntegerCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "BigInts")
    public JAXBElement<TBigIntegerCollection> createBigInts(TBigIntegerCollection value) {
        return new JAXBElement<TBigIntegerCollection>(_BigInts_QNAME, TBigIntegerCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFileCollection }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Files")
    public JAXBElement<TFileCollection> createFiles(TFileCollection value) {
    	System.out.println("element Files created");
        return new JAXBElement<TFileCollection>(_Files_QNAME, TFileCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDoubleCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Doubles")
    public JAXBElement<TDoubleCollection> createDoubles(TDoubleCollection value) {
        return new JAXBElement<TDoubleCollection>(_Doubles_QNAME, TDoubleCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBooleanCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Booleans")
    public JAXBElement<TBooleanCollection> createBooleans(TBooleanCollection value) {
        return new JAXBElement<TBooleanCollection>(_Booleans_QNAME, TBooleanCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStringCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Strings")
    public JAXBElement<TStringCollection> createStrings(TStringCollection value) {
        return new JAXBElement<TStringCollection>(_Strings_QNAME, TStringCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIntCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/types", name = "Ints")
    public JAXBElement<TIntCollection> createInts(TIntCollection value) {
        return new JAXBElement<TIntCollection>(_Ints_QNAME, TIntCollection.class, null, value);
    }
}
