//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 09:31:37 PM CEST 
//

@XmlJavaTypeAdapters(
{
	@XmlJavaTypeAdapter(type = TFileCollection.class, value = FileCollectionAdapter.class),
})
@XmlSchema(
	xmlns = {
		@XmlNs(
			prefix = cz.zcu.kiv.bp.namespaces.DataTypes.SCENARIO_PREFIX,
			namespaceURI = cz.zcu.kiv.bp.namespaces.DataTypes.SCENARIO_URI
		)
	},
	namespace = cz.zcu.kiv.bp.namespaces.DataTypes.SCENARIO_URI,
	location = "file:///D:/SkyDrive/GitHub/kivComponentTesting/CommonTypes/schema/types.xsd", //cz.zcu.kiv.bp.namespaces.DataTypes.SCENARIO_SCHEMA,
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package cz.zcu.kiv.bp.datatypes.bindings;

import cz.zcu.kiv.bp.datatypes.bindings.adapted.FileCollectionAdapter;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapters;