//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.25 at 04:59:18 PM CET 
//


package cz.zcu.kiv.bp.datatypes.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import cz.zcu.kiv.bp.datatypes.bindings.adapted.CustomTypesRegistry;
import cz.zcu.kiv.bp.datatypes.bindings.adapted.CustomTypesRegistryAdapter;


/**
 * <p>Java class for TCustomTypesSupport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TCustomTypesSupport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="types" type="{http://www.kiv.zcu.cz/component-testing/types}TImportedTypes"/>
 *         &lt;element name="values" type="{http://www.kiv.zcu.cz/component-testing/types}TListOfValuesOfImportedTypes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TCustomTypesSupport", propOrder = {
    "listOfTypes",
    "listOfValues"
})
public class TCustomTypesSupport {

    @XmlElement(name = "types", required = false)
    @XmlJavaTypeAdapter(CustomTypesRegistryAdapter.class)
    protected CustomTypesRegistry listOfTypes;
    
    @XmlElement(name = "values", required = false)
    protected TListOfValuesOfImportedTypes listOfValues;

    /**
     * Gets the value of the types property.
     * 
     * @return
     *     possible object is
     *     {@link TImportedTypes }
     *     
     */
    public CustomTypesRegistry getListOfTypes() {
    	if (listOfTypes == null) {
    		listOfTypes = new CustomTypesRegistry();
    	}
        return listOfTypes;
    }

    /**
     * Sets the value of the types property.
     * 
     * @param value
     *     allowed object is
     *     {@link TImportedTypes }
     *     
     */
    public void setListOfTypes(CustomTypesRegistry value) {
        this.listOfTypes = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link TListOfValuesOfImportedTypes }
     *     
     */
    public TListOfValuesOfImportedTypes getListOfValues() {
    	if (listOfValues == null) {
    		listOfValues = new TListOfValuesOfImportedTypes();
    	}
        return listOfValues;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link TListOfValuesOfImportedTypes }
     *     
     */
    public void setListOfValues(TListOfValuesOfImportedTypes value) {
        this.listOfValues = value;
    }

}
