//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.25 at 04:59:18 PM CET 
//


package cz.zcu.kiv.bp.datatypes.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TImportedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TImportedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="factory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="static-member" type="{http://www.kiv.zcu.cz/component-testing/types}TStaticMemberFactory"/>
 *                   &lt;element name="constructor" type="{http://www.kiv.zcu.cz/component-testing/types}TConstructFactory"/>
 *                   &lt;element name="external" type="{http://www.kiv.zcu.cz/component-testing/types}TExternalFactory"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="bundle" type="{http://www.kiv.zcu.cz/component-testing/types}:TBundleName" use="required"/>
 *       &lt;attribute name="version" type="{http://www.kiv.zcu.cz/component-testing/types}:TVersion" use="required" />
 *       &lt;attribute name="cannonical-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TImportedType", propOrder = {
    "factory",
    "cannonicalName",
    "bundle",
    "version"
})
public class TImportedType {

    @XmlElement(required = true)
    protected TImportedType.Factory factory;
    
    @XmlAttribute(name = "cannonical-name", required = true)
    protected String cannonicalName;
    
    @XmlAttribute(name = "bundle", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bundle;
    
    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;

    /**
     * Gets the value of the bundle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundle(String value) {
        this.bundle = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the factory property.
     * 
     * @return
     *     possible object is
     *     {@link TImportedType.Factory }
     *     
     */
    public TImportedType.Factory getFactory() {
        return factory;
    }

    /**
     * Sets the value of the factory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TImportedType.Factory }
     *     
     */
    public void setFactory(TImportedType.Factory value) {
        this.factory = value;
    }

    /**
     * Gets the value of the cannonicalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCannonicalName() {
        return cannonicalName;
    }

    /**
     * Sets the value of the cannonicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCannonicalName(String value) {
        this.cannonicalName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="static-member" type="{http://www.kiv.zcu.cz/component-testing/types}TStaticMemberFactory"/>
     *         &lt;element name="constructor" type="{http://www.kiv.zcu.cz/component-testing/types}TConstructFactory"/>
     *         &lt;element name="external" type="{http://www.kiv.zcu.cz/component-testing/types}TExternalFactory"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "staticMember",
        "constructor",
        "external"
    })
    public static class Factory {

        @XmlElement(name = "static-member")
        protected TStaticMemberFactory staticMember;
        protected TConstructFactory constructor;
        protected TExternalFactory external;

        /**
         * Gets the value of the staticMember property.
         * 
         * @return
         *     possible object is
         *     {@link TStaticMemberFactory }
         *     
         */
        public TStaticMemberFactory getStaticMember() {
            return staticMember;
        }

        /**
         * Sets the value of the staticMember property.
         * 
         * @param value
         *     allowed object is
         *     {@link TStaticMemberFactory }
         *     
         */
        public void setStaticMember(TStaticMemberFactory value) {
            this.staticMember = value;
        }

        /**
         * Gets the value of the constructor property.
         * 
         * @return
         *     possible object is
         *     {@link TConstructFactory }
         *     
         */
        public TConstructFactory getConstructor() {
            return constructor;
        }

        /**
         * Sets the value of the constructor property.
         * 
         * @param value
         *     allowed object is
         *     {@link TConstructFactory }
         *     
         */
        public void setConstructor(TConstructFactory value) {
            this.constructor = value;
        }

        /**
         * Gets the value of the external property.
         * 
         * @return
         *     possible object is
         *     {@link TExternalFactory }
         *     
         */
        public TExternalFactory getExternal() {
            return external;
        }

        /**
         * Sets the value of the external property.
         * 
         * @param value
         *     allowed object is
         *     {@link TExternalFactory }
         *     
         */
        public void setExternal(TExternalFactory value) {
            this.external = value;
        }
    }
}
