//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 09:31:37 PM CEST 
//


package cz.zcu.kiv.bp.unimocker.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.zcu.kiv.bp.unimocker.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Project_QNAME = new QName("http://www.kiv.zcu.cz/component-testing/mocker", "project");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.zcu.kiv.bp.unimocker.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TShortCollection }
     * 
     */
    public TShortCollection createTShortCollection() {
        return new TShortCollection();
    }

    /**
     * Create an instance of {@link TDoubleCollection }
     * 
     */
    public TDoubleCollection createTDoubleCollection() {
        return new TDoubleCollection();
    }

    /**
     * Create an instance of {@link TBigIntegerCollection }
     * 
     */
    public TBigIntegerCollection createTBigIntegerCollection() {
        return new TBigIntegerCollection();
    }

    /**
     * Create an instance of {@link TBooleanCollection }
     * 
     */
    public TBooleanCollection createTBooleanCollection() {
        return new TBooleanCollection();
    }

    /**
     * Create an instance of {@link TLongCollection }
     * 
     */
    public TLongCollection createTLongCollection() {
        return new TLongCollection();
    }

    /**
     * Create an instance of {@link TFileCollection }
     * 
     */
    public TFileCollection createTFileCollection() {
        return new TFileCollection();
    }

    /**
     * Create an instance of {@link TStringCollection }
     * 
     */
    public TStringCollection createTStringCollection() {
        return new TStringCollection();
    }

    /**
     * Create an instance of {@link TBigDecimalCollection }
     * 
     */
    public TBigDecimalCollection createTBigDecimalCollection() {
        return new TBigDecimalCollection();
    }

    /**
     * Create an instance of {@link TFloatCollection }
     * 
     */
    public TFloatCollection createTFloatCollection() {
        return new TFloatCollection();
    }

    /**
     * Create an instance of {@link TByteCollection }
     * 
     */
    public TByteCollection createTByteCollection() {
        return new TByteCollection();
    }

    /**
     * Create an instance of {@link TIntCollection }
     * 
     */
    public TIntCollection createTIntCollection() {
        return new TIntCollection();
    }

    /**
     * Create an instance of {@link TProject }
     * 
     */
    public TProject createTProject() {
        return new TProject();
    }

    /**
     * Create an instance of {@link TNull }
     * 
     */
    public TNull createTNull() {
        return new TNull();
    }

    /**
     * Create an instance of {@link TValue }
     * 
     */
    public TValue createTValue() {
        return new TValue();
    }

    /**
     * Create an instance of {@link TInvokedMethod }
     * 
     */
    public TInvokedMethod createTInvokedMethod() {
        return new TInvokedMethod();
    }

    /**
     * Create an instance of {@link TSimulatedService }
     * 
     */
    public TSimulatedService createTSimulatedService() {
        return new TSimulatedService();
    }

    /**
     * Create an instance of {@link TBundleList }
     * 
     */
    public TBundleList createTBundleList() {
        return new TBundleList();
    }

    /**
     * Create an instance of {@link TArgumentsList }
     * 
     */
    public TArgumentsList createTArgumentsList() {
        return new TArgumentsList();
    }

    /**
     * Create an instance of {@link TBundle }
     * 
     */
    public TBundle createTBundle() {
        return new TBundle();
    }

    /**
     * Create an instance of {@link TInvocation }
     * 
     */
    public TInvocation createTInvocation() {
        return new TInvocation();
    }

    /**
     * Create an instance of {@link TArgument }
     * 
     */
    public TArgument createTArgument() {
        return new TArgument();
    }

    /**
     * Create an instance of {@link TShortCollection.Item }
     * 
     */
    public TShortCollection.Item createTShortCollectionItem() {
        return new TShortCollection.Item();
    }

    /**
     * Create an instance of {@link TDoubleCollection.Item }
     * 
     */
    public TDoubleCollection.Item createTDoubleCollectionItem() {
        return new TDoubleCollection.Item();
    }

    /**
     * Create an instance of {@link TBigIntegerCollection.Item }
     * 
     */
    public TBigIntegerCollection.Item createTBigIntegerCollectionItem() {
        return new TBigIntegerCollection.Item();
    }

    /**
     * Create an instance of {@link TBooleanCollection.Item }
     * 
     */
    public TBooleanCollection.Item createTBooleanCollectionItem() {
        return new TBooleanCollection.Item();
    }

    /**
     * Create an instance of {@link TLongCollection.Item }
     * 
     */
    public TLongCollection.Item createTLongCollectionItem() {
        return new TLongCollection.Item();
    }

    /**
     * Create an instance of {@link TFileCollection.Item }
     * 
     */
    public TFileCollection.Item createTFileCollectionItem() {
        return new TFileCollection.Item();
    }

    /**
     * Create an instance of {@link TStringCollection.Item }
     * 
     */
    public TStringCollection.Item createTStringCollectionItem() {
        return new TStringCollection.Item();
    }

    /**
     * Create an instance of {@link TBigDecimalCollection.Item }
     * 
     */
    public TBigDecimalCollection.Item createTBigDecimalCollectionItem() {
        return new TBigDecimalCollection.Item();
    }

    /**
     * Create an instance of {@link TFloatCollection.Item }
     * 
     */
    public TFloatCollection.Item createTFloatCollectionItem() {
        return new TFloatCollection.Item();
    }

    /**
     * Create an instance of {@link TByteCollection.Item }
     * 
     */
    public TByteCollection.Item createTByteCollectionItem() {
        return new TByteCollection.Item();
    }

    /**
     * Create an instance of {@link TIntCollection.Item }
     * 
     */
    public TIntCollection.Item createTIntCollectionItem() {
        return new TIntCollection.Item();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kiv.zcu.cz/component-testing/mocker", name = "project")
    public JAXBElement<TProject> createProject(TProject value) {
        return new JAXBElement<TProject>(_Project_QNAME, TProject.class, null, value);
    }

}
