//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 09:31:37 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
	xmlns = {
		@javax.xml.bind.annotation.XmlNs(
			prefix = cz.zcu.kiv.bp.namespaces.UniMocker.SCENARIO_PREFIX,
			namespaceURI = cz.zcu.kiv.bp.namespaces.UniMocker.SCENARIO_URI
		)
	},
	namespace = cz.zcu.kiv.bp.namespaces.UniMocker.SCENARIO_URI,
	location = cz.zcu.kiv.bp.namespaces.UniMocker.SCENARIO_SCHEMA,
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package cz.zcu.kiv.bp.unimocker.bindings;
