//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.16 at 09:24:17 PM CET 
//


package cz.zcu.kiv.bp.unimocker.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import cz.zcu.kiv.bp.unimocker.bindings.adapted.BundlesMap;
import cz.zcu.kiv.bp.unimocker.bindings.adapted.BundlesMapAdapter;


/**
 * <p>Java class for TProject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TProject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="simulated-components" type="{http://www.kiv.zcu.cz/component-testing/mocker}TBundleList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TProject", propOrder = {
    "simulatedComponents"
})
public class TProject {

    @XmlElement(name = "simulated-components", type = TBundleList.class)
    @XmlJavaTypeAdapter(BundlesMapAdapter.class)
    protected BundlesMap simulatedComponents;

    /**
     * Gets the value of the simulatedComponents property.
     * 
     * @return
     *     possible object is
     *     {@link TBundleList }
     *     
     */
    public BundlesMap getSimulatedComponents() {
        return simulatedComponents;
    }

    /**
     * Sets the value of the simulatedComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBundleList }
     *     
     */
    public void setSimulatedComponents(BundlesMap value) {
        this.simulatedComponents = value;
    }

}
